name: onlaw
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8 
  http: ^0.13.3
  flutter_local_notifications: ^9.0.1
  email_validator: ^1.0.6
  animate_do: ^2.0.0
  carousel_slider: ^4.0.0
  progressive_image: ^2.0.0
  flutter_svg: ^0.23.0+1
  shared_preferences: ^2.0.8
  flutter_form_builder: ^7.0.0
  intl: ^0.17.0
  form_builder_validators: ^7.2.0
  flutter_breadcrumb: ^1.0.1
  full_screen_image_null_safe: ^2.0.0
  photo_view: ^0.13.0
  file_picker: ^4.2.7
  convex_bottom_bar: ^3.0.0
  diacritic: ^0.1.3
  flutter_credit_card: ^3.0.1
  open_file: ^3.2.1
  path_provider: ^2.0.8
  syncfusion_flutter_pdfviewer: ^19.3.59-beta
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0
  flutter_native_splash: ^1.3.1

flutter_native_splash:
  color: "#282E41"
  #background_image: "assets/background.png"
  image: "assets/image/splash.png"
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  android: true
  ios: true
  web: false 
  android_gravity: center 
  ios_content_mode: center  
  #web_image_mode: center 
  fullscreen: true 
  android12: true

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/font/

  fonts:
    - family: Lemon
      fonts:
        - asset: assets/font/Lemon-Regular.ttf
          weight: 400

